FROM jenkins/ssh-agent:latest

USER root

# install apps
RUN apt-get update && apt-get install -y lsb-release software-properties-common ca-certificates git gcc curl mc
# RUN apt-get install -y curl
# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash
RUN apt-get install -y nodejs
# install yarn
RUN npm install --global yarn

EXPOSE 22
ENTRYPOINT ["setup-sshd"]