version: '3.9'

services:
  jenkins-agent-1:
    container_name: agent1
    privileged: true
    user: root
    restart: always
    ports:
      - 23:22
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile.ssh-agent
    # image: jenkins/ssh-agent:latest
    networks:
      jenkins-net:
        aliases:
          - docker

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - 8081:8080
      - 50000:50000
    env_file:
      - .env
    volumes:
      - ${LOCAL_JENKINS_DIR}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - docker

networks:
  jenkins-net:
    name: jenkins-net
