FROM jenkins/ssh-agent:latest

USER root

# install apps
RUN apt-get update && apt-get install -y lsb-release software-properties-common ca-certificates git gcc curl mc
# RUN apt-get install -y curl
# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash
RUN apt-get install -y nodejs
# install yarn
RUN npm install --global yarn

# RUN apt-get install install  -y 

# install and Docker (client only)
# RUN apt-get update && apt-get install -y lsb-release software-properties-common ca-certificates \
#     install curl \
#     curl -sL https://deb.nodesource.com/setup_18.x | bash - \
#     apt-get install -y nodejs


# RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add
# RUN add-apt-repository
# RUN apt-get install --no-install-recommends -y \
#     apt-transport-https \
#     ca-certificates \
#     curl=${CURL_VERSION} 
    # \
    # git=${GIT_VERSION} \
    # gnupg2 \
    # software-properties-common \
    # && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -\
    # && add-apt-repository \
    # "deb [arch=amd64] https://download.docker.com/linux/debian \
    # $(lsb_release -cs) \
    # stable" \
    # && apt-get update && apt-get install -y \
    # docker-ce-cli=${DOCKER_CE_CLI} \
    # && rm -rf /var/lib/apt/lists/*

EXPOSE 22
ENTRYPOINT ["setup-sshd"]