version: '3.9'

services:
  jenkins-agent-1:
    container_name: agent1
    privileged: true
    user: root
    restart: always
    ports:
      - 22:22
    env_file:
      - .env
    image: jenkins/ssh-agent:5.2.0
    networks:
      jenkins-net:
        aliases:
          - docker

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    env_file:
      - .env
    volumes:
      - ${LOCAL_JENKINS_DIR}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - docker

networks:
  jenkins-net:
    name: jenkins-net
