FROM jenkins/ssh-agent:latest

USER root

# install apps
RUN apt-get update && apt-get install apt-transport-https ca-certificates curl software-properties-common -y
# 
RUN apt-get install -y git gcc curl mc

# install docker
# RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
# RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
# RUN apt-cache policy docker-ce
RUN apt-get install docker.io -y
# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash
RUN apt-get install -y nodejs
# install yarn
RUN npm install --global yarn

EXPOSE 22
ENTRYPOINT ["setup-sshd"]