version: '3.5'

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins-1'
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins-data:/etc/gitlab
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:      

volumes:
  jenkins-data:
    name: jenkins-data
networks:
  jenkins-net: